name: math_keyboard
description: >2-
  Math expression editing using an on-screen software keyboard or physical keyboard input in a
  typeset input field in Flutter.
version: 0.1.7
homepage: https://github.com/simpleclub/math_keyboard/tree/main/math_keyboard
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #flutter_math_fork: ^0.6.3+1
  flutter_math_fork:
    git:
      url: https://github.com/PelephantDevelopment/flutter_math_fork
      ref: 5055bc14ba604410daa29e7b950d500c9d0679a0
  holding_gesture: ^1.1.0
  intl: ^0.18.0
  #math_expressions: ^2.1.0
  math_expressions:
    git:
      url: https://github.com/PelephantDevelopment/math-expressions
      ref: 312d3d8645cde3534a76f6a92aa2a170f923ae83
  petitparser: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0

flutter:
  fonts:
    - family: CustomKeyIcons
      fonts:
        - asset: fonts/CustomKeyIcons.ttf
